name: CI/CD Pipeline for Vue.js with Cypress

on:
  push:
    branches:
      - dev #pr l'instant
  pull_request:
    branches:
      - dev # pr l'instant
  schedule:
    - cron: '0 0 * * *' # Planification pour exécuter tous les jours à minuit (UTC)

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Étape 1 : Vérification du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installation de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      # Étape 3 : Installation des dépendances
      - name: Install dependencies
        run: npm install && npm i

      - name: Add `node_modules/.bin` to PATH
        run: |
          echo "C:\\npm\\node_modules\\.bin" >> $GITHUB_PATH

      #tests unitaires avec vitest
      - name: Run unit tests with Vitest
        run: npm run test:unit
